/*
* @file: ConfigData.h
* @brief: This file is generated by xlstool, please don't edit it.
*/

#include <map>
#include <string>
#include "ConfigDataStorage.pb.h"
#include "Goods.pb.h"
#include "Skill.pb.h"

namespace MyGame {
class ConfigData {
private:
    ConfigDataStorage data_root_;
    std::map<int, const Goods *> Goods_items_;
    std::map<int, const Skill *> Skill_items_;

public:
    const Goods *GetGoods(int id) {
        auto iter = Goods_items_.find(id);
        if(iter != Goods_items_.end()) return iter->second;
        return nullptr;
    }

    const Skill *GetSkill(int id) {
        auto iter = Skill_items_.find(id);
        if(iter != Skill_items_.end()) return iter->second;
        return nullptr;
    }

    bool Init(const std::string &bytes) {
        if (!data_root_.ParseFromString(bytes)) return false;
        for(int i = 0; i < data_root_.goods_items_size(); ++i) {
            const Goods &item = data_root_.goods_items(i);
            Goods_items_[item.id()] = &item;
        }
        for(int i = 0; i < data_root_.skill_items_size(); ++i) {
            const Skill &item = data_root_.skill_items(i);
            Skill_items_[item.id()] = &item;
        }
        return true;
    }
}; // ConfigData
} // MyGame
