// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigDataStorage.proto

#ifndef PROTOBUF_INCLUDED_ConfigDataStorage_2eproto
#define PROTOBUF_INCLUDED_ConfigDataStorage_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Goods.pb.h"
#include "Skill.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ConfigDataStorage_2eproto 

namespace protobuf_ConfigDataStorage_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ConfigDataStorage_2eproto
namespace MyGame {
class ConfigDataStorage;
class ConfigDataStorageDefaultTypeInternal;
extern ConfigDataStorageDefaultTypeInternal _ConfigDataStorage_default_instance_;
}  // namespace MyGame
namespace google {
namespace protobuf {
template<> ::MyGame::ConfigDataStorage* Arena::CreateMaybeMessage<::MyGame::ConfigDataStorage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace MyGame {

// ===================================================================

class ConfigDataStorage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MyGame.ConfigDataStorage) */ {
 public:
  ConfigDataStorage();
  virtual ~ConfigDataStorage();

  ConfigDataStorage(const ConfigDataStorage& from);

  inline ConfigDataStorage& operator=(const ConfigDataStorage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConfigDataStorage(ConfigDataStorage&& from) noexcept
    : ConfigDataStorage() {
    *this = ::std::move(from);
  }

  inline ConfigDataStorage& operator=(ConfigDataStorage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfigDataStorage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConfigDataStorage* internal_default_instance() {
    return reinterpret_cast<const ConfigDataStorage*>(
               &_ConfigDataStorage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ConfigDataStorage* other);
  friend void swap(ConfigDataStorage& a, ConfigDataStorage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConfigDataStorage* New() const final {
    return CreateMaybeMessage<ConfigDataStorage>(NULL);
  }

  ConfigDataStorage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConfigDataStorage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConfigDataStorage& from);
  void MergeFrom(const ConfigDataStorage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConfigDataStorage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .MyGame.Goods Goods_items = 1;
  int goods_items_size() const;
  void clear_goods_items();
  static const int kGoodsItemsFieldNumber = 1;
  ::MyGame::Goods* mutable_goods_items(int index);
  ::google::protobuf::RepeatedPtrField< ::MyGame::Goods >*
      mutable_goods_items();
  const ::MyGame::Goods& goods_items(int index) const;
  ::MyGame::Goods* add_goods_items();
  const ::google::protobuf::RepeatedPtrField< ::MyGame::Goods >&
      goods_items() const;

  // repeated .MyGame.Skill Skill_items = 2;
  int skill_items_size() const;
  void clear_skill_items();
  static const int kSkillItemsFieldNumber = 2;
  ::MyGame::Skill* mutable_skill_items(int index);
  ::google::protobuf::RepeatedPtrField< ::MyGame::Skill >*
      mutable_skill_items();
  const ::MyGame::Skill& skill_items(int index) const;
  ::MyGame::Skill* add_skill_items();
  const ::google::protobuf::RepeatedPtrField< ::MyGame::Skill >&
      skill_items() const;

  // @@protoc_insertion_point(class_scope:MyGame.ConfigDataStorage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::MyGame::Goods > goods_items_;
  ::google::protobuf::RepeatedPtrField< ::MyGame::Skill > skill_items_;
  friend struct ::protobuf_ConfigDataStorage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConfigDataStorage

// repeated .MyGame.Goods Goods_items = 1;
inline int ConfigDataStorage::goods_items_size() const {
  return goods_items_.size();
}
inline ::MyGame::Goods* ConfigDataStorage::mutable_goods_items(int index) {
  // @@protoc_insertion_point(field_mutable:MyGame.ConfigDataStorage.Goods_items)
  return goods_items_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::MyGame::Goods >*
ConfigDataStorage::mutable_goods_items() {
  // @@protoc_insertion_point(field_mutable_list:MyGame.ConfigDataStorage.Goods_items)
  return &goods_items_;
}
inline const ::MyGame::Goods& ConfigDataStorage::goods_items(int index) const {
  // @@protoc_insertion_point(field_get:MyGame.ConfigDataStorage.Goods_items)
  return goods_items_.Get(index);
}
inline ::MyGame::Goods* ConfigDataStorage::add_goods_items() {
  // @@protoc_insertion_point(field_add:MyGame.ConfigDataStorage.Goods_items)
  return goods_items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MyGame::Goods >&
ConfigDataStorage::goods_items() const {
  // @@protoc_insertion_point(field_list:MyGame.ConfigDataStorage.Goods_items)
  return goods_items_;
}

// repeated .MyGame.Skill Skill_items = 2;
inline int ConfigDataStorage::skill_items_size() const {
  return skill_items_.size();
}
inline ::MyGame::Skill* ConfigDataStorage::mutable_skill_items(int index) {
  // @@protoc_insertion_point(field_mutable:MyGame.ConfigDataStorage.Skill_items)
  return skill_items_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::MyGame::Skill >*
ConfigDataStorage::mutable_skill_items() {
  // @@protoc_insertion_point(field_mutable_list:MyGame.ConfigDataStorage.Skill_items)
  return &skill_items_;
}
inline const ::MyGame::Skill& ConfigDataStorage::skill_items(int index) const {
  // @@protoc_insertion_point(field_get:MyGame.ConfigDataStorage.Skill_items)
  return skill_items_.Get(index);
}
inline ::MyGame::Skill* ConfigDataStorage::add_skill_items() {
  // @@protoc_insertion_point(field_add:MyGame.ConfigDataStorage.Skill_items)
  return skill_items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MyGame::Skill >&
ConfigDataStorage::skill_items() const {
  // @@protoc_insertion_point(field_list:MyGame.ConfigDataStorage.Skill_items)
  return skill_items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace MyGame

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ConfigDataStorage_2eproto
