// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigDataStorage.proto

#include "ConfigDataStorage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_Goods_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_Goods_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Goods;
}  // namespace protobuf_Goods_2eproto
namespace protobuf_Skill_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_Skill_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Skill;
}  // namespace protobuf_Skill_2eproto
namespace MyGame {
class ConfigDataStorageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConfigDataStorage>
      _instance;
} _ConfigDataStorage_default_instance_;
}  // namespace MyGame
namespace protobuf_ConfigDataStorage_2eproto {
static void InitDefaultsConfigDataStorage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyGame::_ConfigDataStorage_default_instance_;
    new (ptr) ::MyGame::ConfigDataStorage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyGame::ConfigDataStorage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ConfigDataStorage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsConfigDataStorage}, {
      &protobuf_Goods_2eproto::scc_info_Goods.base,
      &protobuf_Skill_2eproto::scc_info_Skill.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ConfigDataStorage.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyGame::ConfigDataStorage, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyGame::ConfigDataStorage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyGame::ConfigDataStorage, goods_items_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyGame::ConfigDataStorage, skill_items_),
  ~0u,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::MyGame::ConfigDataStorage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::MyGame::_ConfigDataStorage_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "ConfigDataStorage.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\027ConfigDataStorage.proto\022\006MyGame\032\013Goods"
      ".proto\032\013Skill.proto\"[\n\021ConfigDataStorage"
      "\022\"\n\013Goods_items\030\001 \003(\0132\r.MyGame.Goods\022\"\n\013"
      "Skill_items\030\002 \003(\0132\r.MyGame.Skill"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 152);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ConfigDataStorage.proto", &protobuf_RegisterTypes);
  ::protobuf_Goods_2eproto::AddDescriptors();
  ::protobuf_Skill_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ConfigDataStorage_2eproto
namespace MyGame {

// ===================================================================

void ConfigDataStorage::InitAsDefaultInstance() {
}
void ConfigDataStorage::clear_goods_items() {
  goods_items_.Clear();
}
void ConfigDataStorage::clear_skill_items() {
  skill_items_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConfigDataStorage::kGoodsItemsFieldNumber;
const int ConfigDataStorage::kSkillItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConfigDataStorage::ConfigDataStorage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ConfigDataStorage_2eproto::scc_info_ConfigDataStorage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MyGame.ConfigDataStorage)
}
ConfigDataStorage::ConfigDataStorage(const ConfigDataStorage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      goods_items_(from.goods_items_),
      skill_items_(from.skill_items_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:MyGame.ConfigDataStorage)
}

void ConfigDataStorage::SharedCtor() {
}

ConfigDataStorage::~ConfigDataStorage() {
  // @@protoc_insertion_point(destructor:MyGame.ConfigDataStorage)
  SharedDtor();
}

void ConfigDataStorage::SharedDtor() {
}

void ConfigDataStorage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ConfigDataStorage::descriptor() {
  ::protobuf_ConfigDataStorage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ConfigDataStorage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConfigDataStorage& ConfigDataStorage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ConfigDataStorage_2eproto::scc_info_ConfigDataStorage.base);
  return *internal_default_instance();
}


void ConfigDataStorage::Clear() {
// @@protoc_insertion_point(message_clear_start:MyGame.ConfigDataStorage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  goods_items_.Clear();
  skill_items_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ConfigDataStorage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MyGame.ConfigDataStorage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .MyGame.Goods Goods_items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_goods_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .MyGame.Skill Skill_items = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_skill_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MyGame.ConfigDataStorage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MyGame.ConfigDataStorage)
  return false;
#undef DO_
}

void ConfigDataStorage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MyGame.ConfigDataStorage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .MyGame.Goods Goods_items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->goods_items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->goods_items(static_cast<int>(i)),
      output);
  }

  // repeated .MyGame.Skill Skill_items = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->skill_items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->skill_items(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MyGame.ConfigDataStorage)
}

::google::protobuf::uint8* ConfigDataStorage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MyGame.ConfigDataStorage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .MyGame.Goods Goods_items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->goods_items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->goods_items(static_cast<int>(i)), deterministic, target);
  }

  // repeated .MyGame.Skill Skill_items = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->skill_items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->skill_items(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyGame.ConfigDataStorage)
  return target;
}

size_t ConfigDataStorage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyGame.ConfigDataStorage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .MyGame.Goods Goods_items = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->goods_items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->goods_items(static_cast<int>(i)));
    }
  }

  // repeated .MyGame.Skill Skill_items = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->skill_items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->skill_items(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConfigDataStorage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyGame.ConfigDataStorage)
  GOOGLE_DCHECK_NE(&from, this);
  const ConfigDataStorage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConfigDataStorage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyGame.ConfigDataStorage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyGame.ConfigDataStorage)
    MergeFrom(*source);
  }
}

void ConfigDataStorage::MergeFrom(const ConfigDataStorage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyGame.ConfigDataStorage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  goods_items_.MergeFrom(from.goods_items_);
  skill_items_.MergeFrom(from.skill_items_);
}

void ConfigDataStorage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyGame.ConfigDataStorage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConfigDataStorage::CopyFrom(const ConfigDataStorage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyGame.ConfigDataStorage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConfigDataStorage::IsInitialized() const {
  return true;
}

void ConfigDataStorage::Swap(ConfigDataStorage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConfigDataStorage::InternalSwap(ConfigDataStorage* other) {
  using std::swap;
  CastToBase(&goods_items_)->InternalSwap(CastToBase(&other->goods_items_));
  CastToBase(&skill_items_)->InternalSwap(CastToBase(&other->skill_items_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ConfigDataStorage::GetMetadata() const {
  protobuf_ConfigDataStorage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ConfigDataStorage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace MyGame
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MyGame::ConfigDataStorage* Arena::CreateMaybeMessage< ::MyGame::ConfigDataStorage >(Arena* arena) {
  return Arena::CreateInternal< ::MyGame::ConfigDataStorage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
