/*
* @file: ConfigData.cc
* @brief: This file is generated by xlstool, please don't edit it.
*/

#include "ConfigData.h"

namespace MyGame {
bool ConfigData::init(const std::string &bytes) {
    if (!data_root_.ParseFromString(bytes)) return false;
    for(int i = 0; i < data_root_.goods_items_size(); ++i) {
        const Goods &item = data_root_.goods_items(i);
        Goods_items_[item.id()] = &item;
    }
    for(int i = 0; i < data_root_.skill_items_size(); ++i) {
        const Skill &item = data_root_.skill_items(i);
        Skill_items_[item.id()] = &item;
    }
    return true;
}

int ConfigData::Goods_items_size() {
    return data_root_.goods_items_size();
}

const Goods *ConfigData::Goods_items(int index) {
    auto &item = data_root_.goods_items(index);
    return &item;
}

const Goods *ConfigData::getGoods(int id) {
    auto iter = Goods_items_.find(id);
    if(iter != Goods_items_.end()) return iter->second;
    return nullptr;
}

int ConfigData::Skill_items_size() {
    return data_root_.skill_items_size();
}

const Skill *ConfigData::Skill_items(int index) {
    auto &item = data_root_.skill_items(index);
    return &item;
}

const Skill *ConfigData::getSkill(int id) {
    auto iter = Skill_items_.find(id);
    if(iter != Skill_items_.end()) return iter->second;
    return nullptr;
}

} //  MyGame
