/*
* @file: ConfigData.h
* @brief: This file is generated by xlstool, please don't edit it.
*/

#pragma once
#ifndef _XLSTOOL_ConfigData_H
#define _XLSTOOL_ConfigData_H

#include <map>
#include <string>
#include "Goods.pb.h"
#include "Skill.pb.h"
#include "ConfigDataStorage.pb.h"

namespace MyGame {
class ConfigData {
public:
    bool init(const std::string &bytes);
    const Goods *getGoods(int id);
    const Skill *getSkill(int id);

private:
    ConfigDataStorage data_root_;
    std::map<int, const Goods *> Goods_items_;
    std::map<int, const Skill *> Skill_items_;
}; //  ConfigData
} //  MyGame
#endif
