// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataBlocks.proto

#include "DataBlocks.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_Goods_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_Goods_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Goods;
}  // namespace protobuf_Goods_2eproto
namespace protobuf_Skill_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_Skill_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Skill;
}  // namespace protobuf_Skill_2eproto
namespace MyGame {
class DataBlocksDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DataBlocks>
      _instance;
} _DataBlocks_default_instance_;
}  // namespace MyGame
namespace protobuf_DataBlocks_2eproto {
static void InitDefaultsDataBlocks() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::MyGame::_DataBlocks_default_instance_;
    new (ptr) ::MyGame::DataBlocks();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MyGame::DataBlocks::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_DataBlocks =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsDataBlocks}, {
      &protobuf_Skill_2eproto::scc_info_Skill.base,
      &protobuf_Goods_2eproto::scc_info_Goods.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_DataBlocks.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyGame::DataBlocks, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyGame::DataBlocks, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyGame::DataBlocks, skill_items_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MyGame::DataBlocks, goods_items_),
  ~0u,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::MyGame::DataBlocks)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::MyGame::_DataBlocks_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "DataBlocks.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020DataBlocks.proto\022\006MyGame\032\013Skill.proto\032"
      "\013Goods.proto\"T\n\nDataBlocks\022\"\n\013Skill_item"
      "s\030\001 \003(\0132\r.MyGame.Skill\022\"\n\013Goods_items\030\002 "
      "\003(\0132\r.MyGame.Goods"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 138);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DataBlocks.proto", &protobuf_RegisterTypes);
  ::protobuf_Skill_2eproto::AddDescriptors();
  ::protobuf_Goods_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_DataBlocks_2eproto
namespace MyGame {

// ===================================================================

void DataBlocks::InitAsDefaultInstance() {
}
void DataBlocks::clear_skill_items() {
  skill_items_.Clear();
}
void DataBlocks::clear_goods_items() {
  goods_items_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DataBlocks::kSkillItemsFieldNumber;
const int DataBlocks::kGoodsItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DataBlocks::DataBlocks()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DataBlocks_2eproto::scc_info_DataBlocks.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:MyGame.DataBlocks)
}
DataBlocks::DataBlocks(const DataBlocks& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      skill_items_(from.skill_items_),
      goods_items_(from.goods_items_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:MyGame.DataBlocks)
}

void DataBlocks::SharedCtor() {
}

DataBlocks::~DataBlocks() {
  // @@protoc_insertion_point(destructor:MyGame.DataBlocks)
  SharedDtor();
}

void DataBlocks::SharedDtor() {
}

void DataBlocks::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DataBlocks::descriptor() {
  ::protobuf_DataBlocks_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DataBlocks_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DataBlocks& DataBlocks::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DataBlocks_2eproto::scc_info_DataBlocks.base);
  return *internal_default_instance();
}


void DataBlocks::Clear() {
// @@protoc_insertion_point(message_clear_start:MyGame.DataBlocks)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  skill_items_.Clear();
  goods_items_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool DataBlocks::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MyGame.DataBlocks)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .MyGame.Skill Skill_items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_skill_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .MyGame.Goods Goods_items = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_goods_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MyGame.DataBlocks)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MyGame.DataBlocks)
  return false;
#undef DO_
}

void DataBlocks::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MyGame.DataBlocks)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .MyGame.Skill Skill_items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->skill_items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->skill_items(static_cast<int>(i)),
      output);
  }

  // repeated .MyGame.Goods Goods_items = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->goods_items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->goods_items(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MyGame.DataBlocks)
}

::google::protobuf::uint8* DataBlocks::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MyGame.DataBlocks)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .MyGame.Skill Skill_items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->skill_items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->skill_items(static_cast<int>(i)), deterministic, target);
  }

  // repeated .MyGame.Goods Goods_items = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->goods_items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->goods_items(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MyGame.DataBlocks)
  return target;
}

size_t DataBlocks::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MyGame.DataBlocks)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .MyGame.Skill Skill_items = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->skill_items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->skill_items(static_cast<int>(i)));
    }
  }

  // repeated .MyGame.Goods Goods_items = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->goods_items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->goods_items(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DataBlocks::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MyGame.DataBlocks)
  GOOGLE_DCHECK_NE(&from, this);
  const DataBlocks* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DataBlocks>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MyGame.DataBlocks)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MyGame.DataBlocks)
    MergeFrom(*source);
  }
}

void DataBlocks::MergeFrom(const DataBlocks& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MyGame.DataBlocks)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  skill_items_.MergeFrom(from.skill_items_);
  goods_items_.MergeFrom(from.goods_items_);
}

void DataBlocks::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MyGame.DataBlocks)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DataBlocks::CopyFrom(const DataBlocks& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MyGame.DataBlocks)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataBlocks::IsInitialized() const {
  return true;
}

void DataBlocks::Swap(DataBlocks* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DataBlocks::InternalSwap(DataBlocks* other) {
  using std::swap;
  CastToBase(&skill_items_)->InternalSwap(CastToBase(&other->skill_items_));
  CastToBase(&goods_items_)->InternalSwap(CastToBase(&other->goods_items_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DataBlocks::GetMetadata() const {
  protobuf_DataBlocks_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DataBlocks_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace MyGame
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::MyGame::DataBlocks* Arena::CreateMaybeMessage< ::MyGame::DataBlocks >(Arena* arena) {
  return Arena::CreateInternal< ::MyGame::DataBlocks >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
