/*
* @file: ConfigData.cs
* @brief: This file is generated by xlstool, please don't edit it.
*/

using System;
using System.Collections.Generic;

namespace MyGame {
public static class ConfigData {

#region DataBlocks
    private static readonly Dictionary<int, MyGame.Skill> Skill_items_ = new Dictionary<int, MyGame.Skill>();
    private static readonly Dictionary<int, MyGame.Goods> Goods_items_ = new Dictionary<int, MyGame.Goods>();
#endregion

    public static bool Init(byte[] bytes) {
#region Init
        var dataBlocks = ProtoBuf.Serializer.Deserialize<MyGame.DataBlocks>(new System.IO.MemoryStream(bytes));
        if (dataBlocks == null) return false;
        for (int i = 0; i < dataBlocks.Skill_items.Count; ++i) {
            var item = dataBlocks.Skill_items[i];
            Skill_items_[item.id] = item;
        }
        for (int i = 0; i < dataBlocks.Goods_items.Count; ++i) {
            var item = dataBlocks.Goods_items[i];
            Goods_items_[item.id] = item;
        }
        return true;
#endregion
    }

    public static MyGame.Skill Skill(int id) {
        MyGame.Skill item;
        Skill_items_.TryGetValue(id, out item);
        return item;
    }

    public static MyGame.Goods Goods(int id) {
        MyGame.Goods item;
        Goods_items_.TryGetValue(id, out item);
        return item;
    }

}
}
