/*
* @file: ConfigData.cs
* @brief: This file is generated by xlstool, please don't edit it.
*/

using System;
using System.Collections.Generic;

namespace MyGame {
public static class ConfigData {

#region DataBlocks
    private static readonly Dictionary<int, Goods> _GoodsItems = new Dictionary<int, Goods>();
    private static readonly Dictionary<int, Skill> _SkillItems = new Dictionary<int, Skill>();
#endregion

    public static bool Init(byte[] bytes) {
#region Init
        var dataBlocks = ConfigDataStorage.Parser.ParseFrom(bytes);
        if (dataBlocks == null) return false;
        for (int i = 0; i < dataBlocks.GoodsItems.Count; ++i) {
            var item = dataBlocks.GoodsItems[i];
            _GoodsItems[item.Id] = item;
        }
        for (int i = 0; i < dataBlocks.SkillItems.Count; ++i) {
            var item = dataBlocks.SkillItems[i];
            _SkillItems[item.Id] = item;
        }
        return true;
#endregion
    }

    public static Goods GetGoods(int id) {
        Goods item;
        _GoodsItems.TryGetValue(id, out item);
        return item;
    }

    public static Skill GetSkill(int id) {
        Skill item;
        _SkillItems.TryGetValue(id, out item);
        return item;
    }

}
}
