//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: output/proto/Goods.proto
namespace MyGame
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Goods")]
  public partial class Goods : global::ProtoBuf.IExtensible
  {
    public Goods() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _itemName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string itemName
    {
      get { return _itemName; }
      set { _itemName = value; }
    }
    private int _itemLV = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemLV", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemLV
    {
      get { return _itemLV; }
      set { _itemLV = value; }
    }
    private int _UseMinLV = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"UseMinLV", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int UseMinLV
    {
      get { return _UseMinLV; }
      set { _UseMinLV = value; }
    }
    private int _itemMinLvl = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemMinLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemMinLvl
    {
      get { return _itemMinLvl; }
      set { _itemMinLvl = value; }
    }
    private int _itemMaxLvl = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"itemMaxLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemMaxLvl
    {
      get { return _itemMaxLvl; }
      set { _itemMaxLvl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}