//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: output/proto/Skill.proto
namespace MyGame
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Skill")]
  public partial class Skill : global::ProtoBuf.IExtensible
  {
    public Skill() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _skillID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillID
    {
      get { return _skillID; }
      set { _skillID = value; }
    }
    private int _skillIcon = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skillIcon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillIcon
    {
      get { return _skillIcon; }
      set { _skillIcon = value; }
    }
    private string _skillName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"skillName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string skillName
    {
      get { return _skillName; }
      set { _skillName = value; }
    }
    private int _skillLevel = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skillLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillLevel
    {
      get { return _skillLevel; }
      set { _skillLevel = value; }
    }
    private int _skillType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"skillType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int skillType
    {
      get { return _skillType; }
      set { _skillType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}