# -*- coding: utf-8 -*-
# !/usr/bin/env python
# File Name: unity_csharp_codegen.py
# Author: Stan.Lch
# Mail: fn.stanc@gmail.com
# Created Time: 2018/7/15 15:13:33


PROTOGEN_BIN = "protogen"


def output_cs_file_header(package_name, container_name, file_name):
    header = \
'''/*
* @file: %s
* @brief: This file is generated by xlstool, please don't edit it.
*/

using System;
using System.Collections.Generic;

namespace %s {
public static class %s {

'''
    return header % (file_name, package_name, container_name)


def output_cs_file_tail():
    return "}\n}\n"


def output_container_class_member(full_type_name, short_type_name, indent, output):
    member = ' ' * indent + "private static readonly Dictionary<int, {}> {}_items = new Dictionary<int, {}>();\n"
    output.append(member.format(full_type_name, short_type_name, full_type_name))


def output_member_init_code_snippet(full_type_name, short_type_name, indent, output):
    space = ' ' * indent
    output.append("{}for (int i = 0; i < dataBlocks.{}_items.Count; ++i) {{\n".format(space, short_type_name))
    output.append("{}    var item = dataBlocks.{}_items[i];\n".format(space, short_type_name))
    output.append("{}    {}_items[item.id] = item;\n".format(space, short_type_name))
    output.append(space +"}\n")


def begin_init_function(package_name, datablocks_name, indent):
    line = ' ' * indent + "public static void Init({}.{} dataBlocks, System.Action<bool> callback) {{\n"
    return line.format(package_name, datablocks_name)


def end_init_fundtion(indent):
    return ' ' * indent + "}\n\n"


def output_item_getter_function(full_type_name, sheet_name, indent, output):
    output.append(' ' * indent + "public static {} {}(int id) {{\n".format(full_type_name, sheet_name))
    output.append(' ' * indent + "    {} item;\n".format(full_type_name))
    output.append(' ' * indent + "    {}_items.TryGetValue(id, out item);\n".format(sheet_name))
    output.append(' ' * indent + "    return item;\n".format(sheet_name))
    output.append(' ' * indent + "}\n\n")


def gen_code(package_name, container_name, datablocks_name, all_sheet_metas, output_path):
    member_lines = []
    member_init_codes = []
    getter_functions = []
    for xls_file, sheet_metas in all_sheet_metas.items():
        for sheet_meta in sheet_metas:
            sheet_name = sheet_meta.sheet_name
            full_type_name = "{}.{}".format(package_name, sheet_name)

            # output member for data container class
            output_container_class_member(full_type_name, sheet_name, 4, member_lines)

            # output member initialization codes
            output_member_init_code_snippet(full_type_name, sheet_name, 8, member_init_codes)

            output_item_getter_function(full_type_name, sheet_name, 4, getter_functions)
    member_lines.append('\n')

    import os
    file_name = container_name + ".cs"
    file_path = os.path.join(output_path, file_name)
    with open(file_path, "w") as f:
        f.write(output_cs_file_header(package_name, container_name, file_name))
        f.writelines(member_lines)

        f.write(begin_init_function(package_name, datablocks_name, 4))
        f.writelines(member_init_codes)
        f.write(end_init_fundtion(4))

        f.writelines(getter_functions)

        f.write(output_cs_file_tail())
